### PR TITLE
Update unicode_names for newer rusts

### PR DESCRIPTION
**Pull request by antifuchs**
# What does this PR do?

This PR should update `unicode_names` to support more recent rusts - definitely the latest nightly.
# Why?

I tried to include `unicode_names` in a rust 1.8.0 project, and that failed pretty thoroughly: There are inline decls that are now not permitted, and (as I was running tests on nightly), the AST types for `unicode_names_macros` got re-shuffled. 

As I would like to include the base library in a rust 1.10-based project, I hope you will find these changes acceptable & can release them soon (-:

### CODE REVIEW

**Comment by autohuonw** [comment]
Thanks for the pull request, and welcome! You should hear from @huonw (or someone else) soon.

**Comment by antifuchs** [comment]
One thing that I am not sure about is whether I re-generated `src/generated_phf.rs` correctly. I used these commandlines to do so:

``` sh
./target/debug/unicode_names_generator ../data/codepoint_name.csv
./target/debug/unicode_names_generator -p ../data/codepoint_name.csv
```

that is, I didn't pass any of the flags to the generator; please let me know if that's incorrect & I'll regenerate with the correct flags and rebase!

Separately, I wonder how hard it would be to make a cargo command to regenerate these rust files automatically. I'll investigate (-:

**Comment by progval** [comment]
ping?

**Comment by micwoj92** [comment]
@antifuchs  unfortunately this fix does not work anymore (rust 1.62)
```
error: unexpected token: `...`
   --> src/lib.rs:550:32
    |
550 |             for x in lo as u32 ... hi as u32 {
    |                                ^^^
    |
help: use `..` for an exclusive range
    |
550 |             for x in lo as u32 .. hi as u32 {
    |                                ~~
help: or `..=` for an inclusive range
    |
550 |             for x in lo as u32 ..= hi as u32 {
    |                                ~~~

```

Replacing `...` with `..` or `..=` helps, but im not sure if inclusive or exclusive range is needed here.

**Comment by progval** [comment]
@micwoj92 the issue is fixed in my fork: https://github.com/progval/unicode_names2/commit/4885a048c9dd82fbdca8622b7cbc2cb76861b40b

It is available on crates.io: https://crates.io/crates/unicode_names2

**Comment by antifuchs** [comment]
Agreed, you all should be using @progval's fork (I am!) - it's up to date and works with recent rusts.

I'll close this PR. Once/if development on this repo restarts again - please pull in @progval's changes.

**Comment by micwoj92** [comment]
Thanks for mentioning

**Comment by 8573** [comment]
> Replacing `...` with `..` or `..=` helps, but im not sure if inclusive or exclusive range is needed here.

In case you encounter something like this again, note that `...` was a proposed syntax that was stabilized as `..=`.

**Pull request closed without merging**
